/**
 * Expert directory — all 100 experts migrated from the original
 * experts.html, 10 per subject across 10 subjects. Values (ratings,
 * order counts, success rates, credentials, CTA destinations) are the
 * originals; nothing here is generated or sampled.
 */
export interface Expert {
  id: number;
  /** Filter key: accounting | biology | chemistry | cs | finance | math | nursing | exam | sophia | wgu */
  subject: string;
  name: string;
  /** Two-letter monogram drawn into the avatar. */
  initials: string;
  /** Avatar gradient stops, carried over per-expert. */
  gradient: [string, string];
  role: string;
  status: string;
  credentials: string;
  rating: string;
  orders: string;
  successRate: string;
  href: string;
}

export const EXPERTS: Expert[] = [
  {
    id: 0,
    subject: "accounting",
    name: "Sarah M.",
    initials: "SM",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Accounting Expert",
    status: "Available now",
    credentials: "CPA-track · MS Accounting · 8+ yrs experience",
    rating: "4.9",
    orders: "500+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 1,
    subject: "accounting",
    name: "Grace L.",
    initials: "GL",
    gradient: ["#10b981", "#00b854"],
    role: "Accounting Expert",
    status: "Available now",
    credentials: "MS Accounting · 5+ yrs experience",
    rating: "4.8",
    orders: "350+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 2,
    subject: "accounting",
    name: "Sarah K.",
    initials: "SK",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Accounting Expert",
    status: "Available now",
    credentials: "CMA · BS Accounting · 6+ yrs experience",
    rating: "5.0",
    orders: "600+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 3,
    subject: "accounting",
    name: "David R.",
    initials: "DR",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Accounting Expert",
    status: "Available now",
    credentials: "CPA · MBA Accounting · 10+ yrs experience",
    rating: "4.8",
    orders: "580+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 4,
    subject: "accounting",
    name: "Priya Y.",
    initials: "PY",
    gradient: ["#10b981", "#00b854"],
    role: "Accounting Expert",
    status: "",
    credentials: "BS Accounting · QuickBooks Certified · 9+ yrs experience",
    rating: "4.9",
    orders: "540+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 5,
    subject: "accounting",
    name: "James F.",
    initials: "JF",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Accounting Expert",
    status: "",
    credentials: "MS Accounting · Auditing focus · 11+ yrs experience",
    rating: "4.7",
    orders: "680+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 6,
    subject: "accounting",
    name: "Laura M.",
    initials: "LM",
    gradient: ["#f0a500", "#d4880a"],
    role: "Accounting Expert",
    status: "Available now",
    credentials:
      "MS Accounting · Financial Reporting focus · 8+ yrs experience",
    rating: "4.7",
    orders: "280+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 7,
    subject: "accounting",
    name: "Michael T.",
    initials: "MT",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Accounting Expert",
    status: "Available now",
    credentials: "CMA · BS Accounting · 8+ yrs experience",
    rating: "4.8",
    orders: "870+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 8,
    subject: "accounting",
    name: "Angela A.",
    initials: "AA",
    gradient: ["#10b981", "#00b854"],
    role: "Accounting Expert",
    status: "Available now",
    credentials: "CPA · MBA Accounting · 7+ yrs experience",
    rating: "4.8",
    orders: "560+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 9,
    subject: "accounting",
    name: "Robert H.",
    initials: "RH",
    gradient: ["#f0a500", "#d4880a"],
    role: "Accounting Expert",
    status: "Available now",
    credentials: "BS Accounting · QuickBooks Certified · 6+ yrs experience",
    rating: "4.7",
    orders: "500+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 10,
    subject: "biology",
    name: "David K.",
    initials: "DK",
    gradient: ["#f0a500", "#d4880a"],
    role: "Biology Expert",
    status: "Available now",
    credentials: "PhD Biology · 9+ yrs experience",
    rating: "5.0",
    orders: "650+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 11,
    subject: "biology",
    name: "Nina L.",
    initials: "NL",
    gradient: ["#10b981", "#00b854"],
    role: "Biology Expert",
    status: "Available now",
    credentials: "MS Biology · Botany focus · 5+ yrs experience",
    rating: "4.8",
    orders: "810+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 12,
    subject: "biology",
    name: "Kevin S.",
    initials: "KS",
    gradient: ["#10b981", "#00b854"],
    role: "Biology Expert",
    status: "Available now",
    credentials: "MS Molecular Biology · 8+ yrs experience",
    rating: "4.9",
    orders: "310+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 13,
    subject: "biology",
    name: "Grace Z.",
    initials: "GZ",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Biology Expert",
    status: "",
    credentials: "MS Biology · Genetics focus · 12+ yrs experience",
    rating: "5.0",
    orders: "690+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 14,
    subject: "biology",
    name: "Daniel G.",
    initials: "DG",
    gradient: ["#10b981", "#00b854"],
    role: "Biology Expert",
    status: "Available now",
    credentials: "MS Biology · Anatomy & Physiology · 6+ yrs experience",
    rating: "5.0",
    orders: "800+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 15,
    subject: "biology",
    name: "Olivia N.",
    initials: "ON",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Biology Expert",
    status: "",
    credentials: "MS Biology · Marine Biology focus · 5+ yrs experience",
    rating: "4.7",
    orders: "530+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 16,
    subject: "biology",
    name: "Marcus U.",
    initials: "MU",
    gradient: ["#10b981", "#00b854"],
    role: "Biology Expert",
    status: "Available now",
    credentials: "MS Biology · Botany focus · 12+ yrs experience",
    rating: "4.7",
    orders: "720+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 17,
    subject: "biology",
    name: "Aisha B.",
    initials: "AB",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Biology Expert",
    status: "Available now",
    credentials: "MS Molecular Biology · 10+ yrs experience",
    rating: "4.9",
    orders: "750+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 18,
    subject: "biology",
    name: "Ethan I.",
    initials: "EI",
    gradient: ["#f0a500", "#d4880a"],
    role: "Biology Expert",
    status: "Available now",
    credentials: "MS Biology · Genetics focus · 11+ yrs experience",
    rating: "4.9",
    orders: "600+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 19,
    subject: "biology",
    name: "Samantha P.",
    initials: "SP",
    gradient: ["#10b981", "#00b854"],
    role: "Biology Expert",
    status: "Available now",
    credentials: "MS Biology · Anatomy & Physiology · 10+ yrs experience",
    rating: "5.0",
    orders: "780+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 20,
    subject: "chemistry",
    name: "Priya R.",
    initials: "PR",
    gradient: ["#10b981", "#00b854"],
    role: "Chemistry Expert",
    status: "",
    credentials: "PhD Chemistry · 7+ yrs experience",
    rating: "4.9",
    orders: "480+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 21,
    subject: "chemistry",
    name: "Carlos Y.",
    initials: "CY",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Chemistry Expert",
    status: "Available now",
    credentials: "PhD Chemistry · Environmental focus · 5+ yrs experience",
    rating: "4.9",
    orders: "450+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 22,
    subject: "chemistry",
    name: "Rebecca F.",
    initials: "RF",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Chemistry Expert",
    status: "",
    credentials: "PhD Chemistry · 9+ yrs experience",
    rating: "4.9",
    orders: "750+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 23,
    subject: "chemistry",
    name: "Anthony M.",
    initials: "AM",
    gradient: ["#10b981", "#00b854"],
    role: "Chemistry Expert",
    status: "Available now",
    credentials: "PhD Biochemistry · 5+ yrs experience",
    rating: "4.8",
    orders: "500+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 24,
    subject: "chemistry",
    name: "Natalie T.",
    initials: "NT",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Chemistry Expert",
    status: "Available now",
    credentials: "PhD Physical Chemistry · 4+ yrs experience",
    rating: "4.9",
    orders: "410+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 25,
    subject: "chemistry",
    name: "Brian A.",
    initials: "BA",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Chemistry Expert",
    status: "Available now",
    credentials: "PhD Chemistry · Materials focus · 10+ yrs experience",
    rating: "4.8",
    orders: "550+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 26,
    subject: "chemistry",
    name: "Jasmine H.",
    initials: "JH",
    gradient: ["#10b981", "#00b854"],
    role: "Chemistry Expert",
    status: "Available now",
    credentials: "PhD Chemistry · Environmental focus · 8+ yrs experience",
    rating: "4.8",
    orders: "740+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 27,
    subject: "chemistry",
    name: "Victor O.",
    initials: "VO",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Chemistry Expert",
    status: "Available now",
    credentials: "PhD Chemistry · 9+ yrs experience",
    rating: "4.8",
    orders: "410+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 28,
    subject: "chemistry",
    name: "Megan V.",
    initials: "MV",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Chemistry Expert",
    status: "Available now",
    credentials: "PhD Biochemistry · 8+ yrs experience",
    rating: "4.7",
    orders: "900+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 29,
    subject: "chemistry",
    name: "Andre C.",
    initials: "AC",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Chemistry Expert",
    status: "Available now",
    credentials: "PhD Physical Chemistry · 6+ yrs experience",
    rating: "4.8",
    orders: "630+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 30,
    subject: "cs",
    name: "James T.",
    initials: "JT",
    gradient: ["#f0a500", "#d4880a"],
    role: "Computer Science Expert",
    status: "Available now",
    credentials: "MS Computer Science · 6+ yrs experience",
    rating: "4.9",
    orders: "700+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 31,
    subject: "cs",
    name: "Lily C.",
    initials: "LC",
    gradient: ["#10b981", "#00b854"],
    role: "Computer Science Expert",
    status: "Available now",
    credentials: "MS Computer Science · Systems focus · 8+ yrs experience",
    rating: "5.0",
    orders: "950+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 32,
    subject: "cs",
    name: "Trevor J.",
    initials: "TJ",
    gradient: ["#f0a500", "#d4880a"],
    role: "Computer Science Expert",
    status: "Available now",
    credentials: "MS Computer Science · Cloud focus · 10+ yrs experience",
    rating: "5.0",
    orders: "580+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 33,
    subject: "cs",
    name: "Fatima Q.",
    initials: "FQ",
    gradient: ["#f0a500", "#d4880a"],
    role: "Computer Science Expert",
    status: "",
    credentials: "BS Computer Science · Full-Stack focus · 4+ yrs experience",
    rating: "4.9",
    orders: "360+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 34,
    subject: "cs",
    name: "Jordan X.",
    initials: "JX",
    gradient: ["#f0a500", "#d4880a"],
    role: "Computer Science Expert",
    status: "Available now",
    credentials: "MS Computer Science · AI/ML focus · 7+ yrs experience",
    rating: "4.8",
    orders: "740+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 35,
    subject: "cs",
    name: "Christina E.",
    initials: "CE",
    gradient: ["#f0a500", "#d4880a"],
    role: "Computer Science Expert",
    status: "Available now",
    credentials:
      "MS Computer Science · Data Structures focus · 5+ yrs experience",
    rating: "4.9",
    orders: "570+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 36,
    subject: "cs",
    name: "Malik L.",
    initials: "ML",
    gradient: ["#f0a500", "#d4880a"],
    role: "Computer Science Expert",
    status: "Available now",
    credentials: "MS Computer Science · Systems focus · 9+ yrs experience",
    rating: "4.7",
    orders: "840+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 37,
    subject: "cs",
    name: "Hannah S.",
    initials: "HS",
    gradient: ["#10b981", "#00b854"],
    role: "Computer Science Expert",
    status: "Available now",
    credentials: "MS Computer Science · Cloud focus · 8+ yrs experience",
    rating: "4.9",
    orders: "510+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 38,
    subject: "cs",
    name: "Derek Z.",
    initials: "DZ",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Computer Science Expert",
    status: "Available now",
    credentials: "BS Computer Science · Full-Stack focus · 7+ yrs experience",
    rating: "4.8",
    orders: "660+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 39,
    subject: "cs",
    name: "Priyanka G.",
    initials: "PG",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Computer Science Expert",
    status: "",
    credentials: "MS Computer Science · AI/ML focus · 6+ yrs experience",
    rating: "4.8",
    orders: "660+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 40,
    subject: "finance",
    name: "Laura B.",
    initials: "LB",
    gradient: ["#10b981", "#00b854"],
    role: "Finance Expert",
    status: "Available now",
    credentials: "MBA Finance · 10+ yrs experience",
    rating: "5.0",
    orders: "550+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 41,
    subject: "finance",
    name: "Nathan S.",
    initials: "NS",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Finance Expert",
    status: "Available now",
    credentials: "MBA Finance · Risk Management focus · 10+ yrs experience",
    rating: "4.8",
    orders: "880+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 42,
    subject: "finance",
    name: "Amara Z.",
    initials: "AZ",
    gradient: ["#f0a500", "#d4880a"],
    role: "Finance Expert",
    status: "Available now",
    credentials: "CFA-track · MS Economics · 11+ yrs experience",
    rating: "5.0",
    orders: "420+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 43,
    subject: "finance",
    name: "Gregory G.",
    initials: "GG",
    gradient: ["#f0a500", "#d4880a"],
    role: "Finance Expert",
    status: "Available now",
    credentials: "MBA Finance · 7+ yrs experience",
    rating: "4.8",
    orders: "520+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 44,
    subject: "finance",
    name: "Sofia N.",
    initials: "SN",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Finance Expert",
    status: "Available now",
    credentials: "CFA-track · MBA Finance · 11+ yrs experience",
    rating: "4.9",
    orders: "600+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 45,
    subject: "finance",
    name: "Patrick U.",
    initials: "PU",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Finance Expert",
    status: "",
    credentials: "MBA Finance · Real Estate focus · 7+ yrs experience",
    rating: "4.8",
    orders: "700+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 46,
    subject: "finance",
    name: "Chloe B.",
    initials: "CB",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Finance Expert",
    status: "",
    credentials: "MBA Finance · Risk Management focus · 12+ yrs experience",
    rating: "5.0",
    orders: "540+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 47,
    subject: "finance",
    name: "Isaiah I.",
    initials: "II",
    gradient: ["#f0a500", "#d4880a"],
    role: "Finance Expert",
    status: "",
    credentials: "CFA-track · MS Economics · 11+ yrs experience",
    rating: "4.9",
    orders: "910+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 48,
    subject: "finance",
    name: "Vanessa P.",
    initials: "VP",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Finance Expert",
    status: "Available now",
    credentials: "MBA Finance · 12+ yrs experience",
    rating: "4.7",
    orders: "570+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 49,
    subject: "finance",
    name: "Tyler W.",
    initials: "TW",
    gradient: ["#f0a500", "#d4880a"],
    role: "Finance Expert",
    status: "Available now",
    credentials: "CFA-track · MBA Finance · 5+ yrs experience",
    rating: "4.7",
    orders: "760+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 50,
    subject: "math",
    name: "Michael S.",
    initials: "MS",
    gradient: ["#10b981", "#00b854"],
    role: "Math Expert",
    status: "Available now",
    credentials: "PhD Mathematics · 8+ yrs experience",
    rating: "4.9",
    orders: "800+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 51,
    subject: "math",
    name: "Daniel F.",
    initials: "DF",
    gradient: ["#f0a500", "#d4880a"],
    role: "Math Expert",
    status: "Available now",
    credentials: "MS Applied Mathematics · 7+ yrs experience",
    rating: "4.9",
    orders: "610+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 52,
    subject: "math",
    name: "Leah A.",
    initials: "LA",
    gradient: ["#f0a500", "#d4880a"],
    role: "Math Expert",
    status: "",
    credentials: "MS Mathematics · Discrete Math focus · 12+ yrs experience",
    rating: "4.9",
    orders: "300+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 53,
    subject: "math",
    name: "Marcus H.",
    initials: "MH",
    gradient: ["#10b981", "#00b854"],
    role: "Math Expert",
    status: "Available now",
    credentials: "MS Statistics · 8+ yrs experience",
    rating: "4.9",
    orders: "300+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 54,
    subject: "math",
    name: "Jenna O.",
    initials: "JO",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Math Expert",
    status: "Available now",
    credentials: "PhD Mathematics · Number Theory focus · 12+ yrs experience",
    rating: "4.9",
    orders: "360+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 55,
    subject: "math",
    name: "Omar V.",
    initials: "OV",
    gradient: ["#10b981", "#00b854"],
    role: "Math Expert",
    status: "Available now",
    credentials: "MS Applied Mathematics · 10+ yrs experience",
    rating: "4.8",
    orders: "710+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 56,
    subject: "math",
    name: "Rachel C.",
    initials: "RC",
    gradient: ["#10b981", "#00b854"],
    role: "Math Expert",
    status: "Available now",
    credentials: "MS Mathematics · Calculus focus · 11+ yrs experience",
    rating: "4.7",
    orders: "470+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 57,
    subject: "math",
    name: "Ian J.",
    initials: "IJ",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Math Expert",
    status: "Available now",
    credentials: "MS Mathematics · Discrete Math focus · 11+ yrs experience",
    rating: "5.0",
    orders: "920+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 58,
    subject: "math",
    name: "Sarah Q.",
    initials: "SQ",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Math Expert",
    status: "Available now",
    credentials: "MS Statistics · 6+ yrs experience",
    rating: "4.8",
    orders: "550+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 59,
    subject: "math",
    name: "David X.",
    initials: "DX",
    gradient: ["#10b981", "#00b854"],
    role: "Math Expert",
    status: "",
    credentials: "PhD Mathematics · Number Theory focus · 5+ yrs experience",
    rating: "4.7",
    orders: "600+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 60,
    subject: "nursing",
    name: "Angela W.",
    initials: "AW",
    gradient: ["#10b981", "#00b854"],
    role: "Nursing Expert",
    status: "Available now",
    credentials: "MSN, RN · 9+ yrs experience",
    rating: "5.0",
    orders: "600+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 61,
    subject: "nursing",
    name: "Priya H.",
    initials: "PH",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Nursing Expert",
    status: "Available now",
    credentials: "MSN, FNP-BC · 7+ yrs experience",
    rating: "4.8",
    orders: "400+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 62,
    subject: "nursing",
    name: "James O.",
    initials: "JO",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Nursing Expert",
    status: "Available now",
    credentials: "DNP, RN · Community Health focus · 6+ yrs experience",
    rating: "4.7",
    orders: "840+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 63,
    subject: "nursing",
    name: "Laura V.",
    initials: "LV",
    gradient: ["#10b981", "#00b854"],
    role: "Nursing Expert",
    status: "Available now",
    credentials: "MSN, PMHNP · 10+ yrs experience",
    rating: "4.9",
    orders: "570+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 64,
    subject: "nursing",
    name: "Michael C.",
    initials: "MC",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Nursing Expert",
    status: "",
    credentials: "MSN, RN-BC · Education focus · 5+ yrs experience",
    rating: "4.8",
    orders: "840+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 65,
    subject: "nursing",
    name: "Angela J.",
    initials: "AJ",
    gradient: ["#f0a500", "#d4880a"],
    role: "Nursing Expert",
    status: "Available now",
    credentials: "DNP, RN · 8+ yrs experience",
    rating: "4.8",
    orders: "410+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 66,
    subject: "nursing",
    name: "Robert Q.",
    initials: "RQ",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Nursing Expert",
    status: "Available now",
    credentials: "MSN, FNP-BC · 11+ yrs experience",
    rating: "4.9",
    orders: "630+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 67,
    subject: "nursing",
    name: "Nina X.",
    initials: "NX",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Nursing Expert",
    status: "Available now",
    credentials: "DNP, RN · Community Health focus · 12+ yrs experience",
    rating: "4.9",
    orders: "630+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 68,
    subject: "nursing",
    name: "Kevin E.",
    initials: "KE",
    gradient: ["#10b981", "#00b854"],
    role: "Nursing Expert",
    status: "Available now",
    credentials: "MSN, PMHNP · 11+ yrs experience",
    rating: "4.7",
    orders: "560+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 69,
    subject: "nursing",
    name: "Grace L.",
    initials: "GL",
    gradient: ["#10b981", "#00b854"],
    role: "Nursing Expert",
    status: "Available now",
    credentials: "MSN, RN-BC · Education focus · 7+ yrs experience",
    rating: "5.0",
    orders: "690+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 70,
    subject: "exam",
    name: "Robert C.",
    initials: "RC",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Online Exam Specialist",
    status: "Available now",
    credentials: "Multi-subject · 7+ yrs experience",
    rating: "4.9",
    orders: "900+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 71,
    subject: "exam",
    name: "Daniel P.",
    initials: "DP",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Online Exam Specialist",
    status: "Available now",
    credentials: "Multi-subject · Humanities focus · 6+ yrs experience",
    rating: "4.8",
    orders: "670+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 72,
    subject: "exam",
    name: "Olivia W.",
    initials: "OW",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Online Exam Specialist",
    status: "Available now",
    credentials: "Multi-subject · Proctored-exam focus · 12+ yrs experience",
    rating: "4.9",
    orders: "740+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 73,
    subject: "exam",
    name: "Marcus D.",
    initials: "MD",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Online Exam Specialist",
    status: "Available now",
    credentials: "Multi-subject · Health Sciences focus · 7+ yrs experience",
    rating: "4.8",
    orders: "360+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 74,
    subject: "exam",
    name: "Aisha K.",
    initials: "AK",
    gradient: ["#10b981", "#00b854"],
    role: "Online Exam Specialist",
    status: "Available now",
    credentials: "Multi-subject · Statistics & Math focus · 8+ yrs experience",
    rating: "4.9",
    orders: "320+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 75,
    subject: "exam",
    name: "Ethan R.",
    initials: "ER",
    gradient: ["#10b981", "#00b854"],
    role: "Online Exam Specialist",
    status: "Available now",
    credentials: "Multi-subject · 5+ yrs experience",
    rating: "5.0",
    orders: "930+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 76,
    subject: "exam",
    name: "Samantha Y.",
    initials: "SY",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Online Exam Specialist",
    status: "Available now",
    credentials: "Multi-subject · Humanities focus · 11+ yrs experience",
    rating: "4.8",
    orders: "790+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 77,
    subject: "exam",
    name: "Carlos F.",
    initials: "CF",
    gradient: ["#10b981", "#00b854"],
    role: "Online Exam Specialist",
    status: "Available now",
    credentials: "Multi-subject · Proctored-exam focus · 11+ yrs experience",
    rating: "4.8",
    orders: "700+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 78,
    subject: "exam",
    name: "Rebecca M.",
    initials: "RM",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Online Exam Specialist",
    status: "Available now",
    credentials: "Multi-subject · Health Sciences focus · 9+ yrs experience",
    rating: "4.9",
    orders: "720+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 79,
    subject: "exam",
    name: "Anthony T.",
    initials: "AT",
    gradient: ["#3b82f6", "#2563eb"],
    role: "Online Exam Specialist",
    status: "",
    credentials: "Multi-subject · Statistics & Math focus · 7+ yrs experience",
    rating: "4.9",
    orders: "600+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 80,
    subject: "sophia",
    name: "Nina P.",
    initials: "NP",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Sophia Learning Expert",
    status: "",
    credentials: "Multi-subject · 6+ yrs experience",
    rating: "4.9",
    orders: "400+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 81,
    subject: "sophia",
    name: "Natalie C.",
    initials: "NC",
    gradient: ["#10b981", "#00b854"],
    role: "Sophia Learning Expert",
    status: "",
    credentials: "Multi-subject · Gen-Ed focus · 11+ yrs experience",
    rating: "4.9",
    orders: "640+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 82,
    subject: "sophia",
    name: "Brian J.",
    initials: "BJ",
    gradient: ["#10b981", "#00b854"],
    role: "Sophia Learning Expert",
    status: "",
    credentials: "Multi-subject · Milestone specialist · 10+ yrs experience",
    rating: "5.0",
    orders: "400+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 83,
    subject: "sophia",
    name: "Jasmine Q.",
    initials: "JQ",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Sophia Learning Expert",
    status: "Available now",
    credentials: "Multi-subject · Fast-track focus · 9+ yrs experience",
    rating: "5.0",
    orders: "710+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 84,
    subject: "sophia",
    name: "Victor X.",
    initials: "VX",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Sophia Learning Expert",
    status: "Available now",
    credentials:
      "Multi-subject · Humanities Pathway focus · 12+ yrs experience",
    rating: "4.9",
    orders: "880+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 85,
    subject: "sophia",
    name: "Megan E.",
    initials: "ME",
    gradient: ["#06b6d4", "#0099cc"],
    role: "Sophia Learning Expert",
    status: "Available now",
    credentials: "Multi-subject · Transfer-credit focus · 8+ yrs experience",
    rating: "4.8",
    orders: "550+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 86,
    subject: "sophia",
    name: "Andre L.",
    initials: "AL",
    gradient: ["#10b981", "#00b854"],
    role: "Sophia Learning Expert",
    status: "Available now",
    credentials: "Multi-subject · Gen-Ed focus · 8+ yrs experience",
    rating: "5.0",
    orders: "350+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 87,
    subject: "sophia",
    name: "Lily S.",
    initials: "LS",
    gradient: ["#10b981", "#00b854"],
    role: "Sophia Learning Expert",
    status: "Available now",
    credentials: "Multi-subject · Milestone specialist · 9+ yrs experience",
    rating: "4.8",
    orders: "720+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 88,
    subject: "sophia",
    name: "Trevor Z.",
    initials: "TZ",
    gradient: ["#f0a500", "#d4880a"],
    role: "Sophia Learning Expert",
    status: "Available now",
    credentials: "Multi-subject · Fast-track focus · 10+ yrs experience",
    rating: "5.0",
    orders: "410+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 89,
    subject: "sophia",
    name: "Fatima G.",
    initials: "FG",
    gradient: ["#f0a500", "#d4880a"],
    role: "Sophia Learning Expert",
    status: "Available now",
    credentials:
      "Multi-subject · Humanities Pathway focus · 12+ yrs experience",
    rating: "4.7",
    orders: "550+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 90,
    subject: "wgu",
    name: "Kevin H.",
    initials: "KH",
    gradient: ["#06b6d4", "#0099cc"],
    role: "WGU Coursework Expert",
    status: "Available now",
    credentials: "OA/PA Specialist · 8+ yrs experience",
    rating: "5.0",
    orders: "520+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 91,
    subject: "wgu",
    name: "Jordan K.",
    initials: "JK",
    gradient: ["#10b981", "#00b854"],
    role: "WGU Coursework Expert",
    status: "",
    credentials: "OA/PA Specialist · 7+ yrs experience",
    rating: "4.7",
    orders: "300+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 92,
    subject: "wgu",
    name: "Christina R.",
    initials: "CR",
    gradient: ["#f0a500", "#d4880a"],
    role: "WGU Coursework Expert",
    status: "Available now",
    credentials: "OA/PA Specialist · Business focus · 5+ yrs experience",
    rating: "4.8",
    orders: "920+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 93,
    subject: "wgu",
    name: "Malik Y.",
    initials: "MY",
    gradient: ["#10b981", "#00b854"],
    role: "WGU Coursework Expert",
    status: "Available now",
    credentials: "OA/PA Specialist · Teaching focus · 8+ yrs experience",
    rating: "4.9",
    orders: "480+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 94,
    subject: "wgu",
    name: "Hannah F.",
    initials: "HF",
    gradient: ["#f0a500", "#d4880a"],
    role: "WGU Coursework Expert",
    status: "Available now",
    credentials: "OA/PA Specialist · Task-2/3 focus · 12+ yrs experience",
    rating: "4.9",
    orders: "480+",
    successRate: "96%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 95,
    subject: "wgu",
    name: "Derek M.",
    initials: "DM",
    gradient: ["#f0a500", "#d4880a"],
    role: "WGU Coursework Expert",
    status: "Available now",
    credentials:
      "OA/PA Specialist · Performance Assessment focus · 9+ yrs experience",
    rating: "4.8",
    orders: "740+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 96,
    subject: "wgu",
    name: "Priyanka T.",
    initials: "PT",
    gradient: ["#10b981", "#00b854"],
    role: "WGU Coursework Expert",
    status: "",
    credentials: "OA/PA Specialist · 9+ yrs experience",
    rating: "4.8",
    orders: "460+",
    successRate: "98%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 97,
    subject: "wgu",
    name: "Nathan A.",
    initials: "NA",
    gradient: ["#06b6d4", "#0099cc"],
    role: "WGU Coursework Expert",
    status: "",
    credentials: "OA/PA Specialist · Business focus · 10+ yrs experience",
    rating: "4.7",
    orders: "710+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 98,
    subject: "wgu",
    name: "Amara H.",
    initials: "AH",
    gradient: ["#10b981", "#00b854"],
    role: "WGU Coursework Expert",
    status: "Available now",
    credentials: "OA/PA Specialist · Teaching focus · 11+ yrs experience",
    rating: "5.0",
    orders: "550+",
    successRate: "99%",
    href: "https://myonlineclasspro.com/place-order",
  },
  {
    id: 99,
    subject: "wgu",
    name: "Gregory O.",
    initials: "GO",
    gradient: ["#3b82f6", "#2563eb"],
    role: "WGU Coursework Expert",
    status: "Available now",
    credentials: "OA/PA Specialist · Task-2/3 focus · 7+ yrs experience",
    rating: "4.9",
    orders: "370+",
    successRate: "97%",
    href: "https://myonlineclasspro.com/place-order",
  },
];

export interface SubjectOption {
  value: string;
  label: string;
}

/** Filter chips for Browse All Experts, in the original order. */
export const SUBJECT_FILTERS: SubjectOption[] = [
  { value: "all", label: "All Experts" },
  { value: "accounting", label: "Accounting" },
  { value: "biology", label: "Biology" },
  { value: "chemistry", label: "Chemistry" },
  { value: "cs", label: "Computer Science" },
  { value: "finance", label: "Finance" },
  { value: "math", label: "Math" },
  { value: "nursing", label: "Nursing" },
  { value: "exam", label: "Online Exams" },
  { value: "sophia", label: "Sophia Learning" },
  { value: "wgu", label: "WGU" },
];

/** Matcher step 1 — same subjects, minus the "all" pseudo-filter. */
export const MATCH_SUBJECTS: SubjectOption[] = SUBJECT_FILTERS.filter(
  (s) => s.value !== "all",
);

/** Matcher step 2 — urgency, with the original messaging. */
export const URGENCY_OPTIONS = [
  {
    value: "today",
    label: "Today",
    message: "Rush assignment - expert can start within the hour.",
  },
  {
    value: "week",
    label: "This Week",
    message: "Weekly coursework - expert has capacity this week.",
  },
  {
    value: "flex",
    label: "No Rush",
    message: "Flexible timeline - expert will plan around your deadlines.",
  },
] as const;

export const EXPERT_FAQS = [
  {
    q: "Why should I hire experts from MyOnlineClassPro?",
    a: "If you're looking for experts with years of experience handling online courses and a proven track record, give us a try. We match you with specialists suited to deliver exceptional results for your exact subject.",
  },
  {
    q: "How can I know more about your experts?",
    a: "You can review each expert's subject focus, experience, rating, and completed-order history right on this page. For more specific questions about an expert's academic background, just ask our support team.",
  },
  {
    q: "How do you hire your experts?",
    a: "Every expert goes through a multi-level hiring process where we evaluate academic achievements, quality of work, on-time delivery, and prior course completions, so only industry-leading talent makes it onto our team.",
  },
  {
    q: "Are your experts familiar with major LMS platforms?",
    a: "Yes. Our experts are well versed in all major LMS platforms and have completed thousands of courses across them, so your specific platform is very unlikely to be unfamiliar territory.",
  },
  {
    q: "Will I be able to directly communicate with my expert?",
    a: "Yes. Once you hire an expert, you have complete freedom to connect with them directly, check on progress, and review their work throughout the entire process.",
  },
  {
    q: "Can I hire an expert on an urgent basis?",
    a: "Yes. For urgent requirements, you can hire our experts and have your work prioritized accordingly.",
  },
];

/** "How We Match You With an Expert" — original three steps. */
export const MATCH_STEPS = [
  {
    title: "Tell Us Your Subject",
    body: "Share your course, syllabus, and deadlines through the order form or WhatsApp.",
  },
  {
    title: "We Match the Right Specialist",
    body: "We pair you with a vetted expert in that exact subject - not a generalist.",
  },
  {
    title: "Track Progress Until Completion",
    body: "Get regular updates and stay in touch with support until your course is complete.",
  },
];
